[build]
  command = "npm run build"
  publish = "build"


[build.environment]
  NPM_FLAGS="--prefix=/dev/null"
 
[dev]
 command = "svelte-kit dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
